# SERIES

In [6]:
import pandas as pd
import numpy as np

In [7]:
lst = [5,7,11,-1,4]
print(lst)

[5, 7, 11, -1, 4]


In [8]:
nar = np.array([5,7,11,-1,4])
print(nar)

[ 5  7 11 -1  4]


In [9]:
ser  =pd.Series([5,7,11,-1,4])
print(ser)

0     5
1     7
2    11
3    -1
4     4
dtype: int64


In [10]:
print(ser.index)

RangeIndex(start=0, stop=5, step=1)


In [11]:
print(ser[2])

11


In [12]:
print(nar[2])

11


In [13]:
ser1  =pd.Series([5,7,11,-1,4], index = ['a','b','c','d','a'])
print(ser1)

a     5
b     7
c    11
d    -1
a     4
dtype: int64


In [14]:
print(ser1['a'])

a    5
a    4
dtype: int64


In [15]:
ser1.index = ['r1','r2','r3','r4','r5']

In [16]:
print(ser1)

r1     5
r2     7
r3    11
r4    -1
r5     4
dtype: int64


In [17]:
#index con
idx = pd.Index([1,2,3,4,5])
ser3 = pd.Series([5,7,11,-1,4], index = idx)
print(ser3)

1     5
2     7
3    11
4    -1
5     4
dtype: int64


In [18]:
idx = pd.Index([1,2,3,4,5])
ser4 = pd.Series([5,7,11,-1,4,2], index = idx)
print(ser3)

ValueError: Length of values (6) does not match length of index (5)

In [19]:
#name att
ser1.name = "first series"
print(ser1)

r1     5
r2     7
r3    11
r4    -1
r5     4
Name: first series, dtype: int64


In [20]:
#pd.Series(data, index, dtype, name ,copy)
idx = pd.Index([1,2,3,4,5])
ser4 = pd.Series([5,7,11,-1,4], index = idx, dtype = float)
print(ser4)

1     5.0
2     7.0
3    11.0
4    -1.0
5     4.0
dtype: float64


In [21]:
#narray
nda = np.array([3,4,5,6,7])
print(nda)

[3 4 5 6 7]


In [22]:
print(nda.dtype)

int32


In [23]:
ser5 = pd.Series(nda)
print(ser5)

0    3
1    4
2    5
3    6
4    7
dtype: int32


In [24]:
n = np.array([1,2,3,4])
ser = pd.Series(n)
print(ser)

0    1
1    2
2    3
3    4
dtype: int32


In [25]:
n[3] = 0
print(ser)

0    1
1    2
2    3
3    0
dtype: int32


In [26]:
ser7 = pd.Series(n,copy = True)
print(ser7)

0    1
1    2
2    3
3    0
dtype: int32


In [27]:
n[3] = 45

In [28]:
print(n)

[ 1  2  3 45]


In [29]:
print(ser7)

0    1
1    2
2    3
3    0
dtype: int32


In [30]:
ser8 = pd.Series(np.random.rand(5))
print(ser8)

0    0.508892
1    0.146523
2    0.171069
3    0.165491
4    0.566878
dtype: float64


In [31]:
ser9 = pd.Series(np.arange(1,6))
print(ser9)

0    1
1    2
2    3
3    4
4    5
dtype: int32


In [32]:
ser10 = pd.Series(np.zeros(4))
print(ser10)

0    0.0
1    0.0
2    0.0
3    0.0
dtype: float64


In [35]:
#scalar
ser11 = pd.Series(4,index = [1,2,3,4])
print(ser11)

1    4
2    4
3    4
4    4
dtype: int64


In [36]:
#dic
dic = {'a':12,'b':34,'c':56}
ser12 = pd.Series(dic)
print(ser12)

a    12
b    34
c    56
dtype: int64
