## 1. Index and slicing

In [1]:
import numpy as np

### One-dimensional arrays

Indexing

In [2]:
a = np.arange(0, 11)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a[0]  # the first element

0

In [5]:
a[-1] # the last element

10

In [6]:
a[4]  # the fifth element, at index 4

4

Slicing

In [7]:
#[m:n:1]
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [9]:
a[:5]

array([0, 1, 2, 3, 4])

In [10]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [11]:
a[::-2]


array([10,  8,  6,  4,  2,  0])

## Multidimensional arrays

In [12]:
f = lambda m, n: n + 10 * m

In [13]:
A = np.fromfunction(f, (6, 6), dtype=int)

In [14]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [15]:
A[:, 1]  # the second column

array([ 1, 11, 21, 31, 41, 51])

In [16]:
A[1, :]  # the second row

array([10, 11, 12, 13, 14, 15])

In [17]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [18]:
A[:3, :3]  # upper half diagonal block matrix

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [19]:
A[3:, :3]  # lower left off-diagonal block matrix

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [20]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [21]:
A[::2, ::2]  # every second element starting from 0, 0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [22]:
A[1::2, 1::3]  # every second element and third element starting from 1, 1

array([[11, 14],
       [31, 34],
       [51, 54]])

### Views

In [23]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [24]:
B = A[1:5, 1:5]

In [25]:
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [26]:
B[:, :] = 0

In [27]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [28]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
C = B[1:3, 1:3].copy()

In [30]:
C

array([[0, 0],
       [0, 0]])

In [31]:
C[:, :] = 1  # this does not affect B since C is a copy of the view B[1:3, 1:3]

In [32]:
C

array([[1, 1],
       [1, 1]])

In [33]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Boolean-valued indexing

In [34]:
A = np.linspace(0, 1, 11)

In [35]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [36]:
A[[0, 2, 4]]

array([0. , 0.2, 0.4])

In [37]:
A > 0.5 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [38]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [39]:
A = np.arange(10)

In [40]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
indices = [2, 4, 6]

In [42]:
B = A[indices]

In [43]:
B[0] = -1  # this does not affect A

In [44]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
A[indices] = -1

In [46]:
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

In [47]:
A = np.arange(10)

In [48]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
B = A[A > 5]

In [50]:
B

array([6, 7, 8, 9])

In [51]:
B[0] = -1  # this does not affect A

In [52]:
B

array([-1,  7,  8,  9])

In [53]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
A[A > 5] = -1

In [55]:
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

## Reshaping and resizing

In [56]:
data = np.array([[1, 2], [3, 4]])

In [57]:
data

array([[1, 2],
       [3, 4]])

In [58]:
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [59]:
data.reshape(4)

array([1, 2, 3, 4])

In [60]:
data = np.array([[1, 2], [3, 4]])

In [61]:
data

array([[1, 2],
       [3, 4]])

In [62]:
data.flatten()

array([1, 2, 3, 4])

In [63]:
data.flatten().shape

(4,)

In [64]:
data = np.arange(0, 5)

In [65]:
data

array([0, 1, 2, 3, 4])

In [66]:
column = data[:, np.newaxis]

In [67]:
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [68]:
row = data[np.newaxis, :]

In [69]:
row

array([[0, 1, 2, 3, 4]])

In [70]:
data = np.arange(5)

In [71]:
data

array([0, 1, 2, 3, 4])

In [72]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [73]:
data = np.arange(5)

In [74]:
data

array([0, 1, 2, 3, 4])

In [75]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [76]:
data = data[:, np.newaxis]

In [77]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])