### Anatomy of an array

<img src="img/numpy-anatomy-of-an-array-updated.png" alt="anatomy of a numpy array"/>

Key terms:
* **Array** - A list of numbers, can be multi-dimensional.
* **Scalar** - A single number (e.g. `7`).
* **Vector** - A list of numbers with 1-dimesion (e.g. `np.array([1, 2, 3])`).
* **Matrix** - A (usually) multi-deminsional list of numbers (e.g. `np.array([[1, 2, 3], [4, 5, 6]])`).

## Creating arrays

* `np.array()`
* `np.ones()`
* `np.zeros()`
* `np.random.rand(5, 3)`
* `np.random.randint(10, size=5)`
* `np.random.seed()` - pseudo random numbers


In [1]:
import numpy as np

In [2]:
num_list = [10,12,14,16,20]
num_array = np.array(num_list)


In [3]:
type(num_array)

numpy.ndarray

In [4]:
row1 = [10, 12, 13]
row2 = [45,56,49]
row3 = [ 23,56,89]
num_2d = np.array([row1, row2, row3])

In [5]:
num_2d

array([[10, 12, 13],
       [45, 56, 49],
       [23, 56, 89]])

In [6]:
num_2d.shape

(3, 3)

In [7]:
# arange 

# (lower, upper, step)

num_arr = np.arange(5,11)
print(num_arr)

[ 5  6  7  8  9 10]


In [8]:
num_arr = np.arange(5,11,2)
print(num_arr)

[5 7 9]


In [9]:
# ones
arr_ones = np.ones(6)
print(arr_ones)

[1. 1. 1. 1. 1. 1.]


In [10]:
arr_ones2 = np.ones((6,4))
print(arr_ones2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
#zeros
arr_zeros = np.zeros(6)

In [12]:
print(arr_zeros)

[0. 0. 0. 0. 0. 0.]


In [13]:
arr_zeros2 = np.zeros((6,4))
print(arr_zeros2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
# eye
arr_eye = np.eye(3)
print(arr_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
arr_eye = np.eye(5)
print(arr_eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# random
# random.rand
unif_random = np.random.rand(2,3)
print(unif_random)

[[0.97601528 0.30162266 0.79485954]
 [0.38673172 0.39122197 0.19583094]]


In [17]:
# randn
nor_random = np.random.randn(3,3)
print(nor_random)

[[ 1.46506797  0.37064357 -1.44443291]
 [-0.96888912 -0.92490993  0.37488357]
 [ 1.34966568 -0.25508024 -0.15311864]]


In [18]:
# randint
int_random = np.random.randint(10, 50, 5)
print(int_random)

[38 21 44 21 30]


In [19]:
# Adding element

# append()
my_arr = np.array(['Red', 'Yellow', 'Green'])
print(my_arr)

['Red' 'Yellow' 'Green']


In [20]:
extended = np.append(my_arr, "blue")
print(extended)

['Red' 'Yellow' 'Green' 'blue']


In [21]:
extended = np.append(my_arr, ['black', 'white'])
print(extended)

['Red' 'Yellow' 'Green' 'black' 'white']


In [22]:
zero_arr = np.zeros((3,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
print(zero_arr)
print("Extended")
extend = np.append(zero_arr, [[1,2,3]], axis = 0)
print(extend)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Extended
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 2. 3.]]


In [25]:
print(zero_arr)
print("Extended")
extend = np.append(zero_arr, [[1],[2],[3]], axis = 1)
print(extend)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Extended
[[0. 0. 0. 1.]
 [0. 0. 0. 2.]
 [0. 0. 0. 3.]]


In [26]:
# Removing
# delete()
print(extended)

['Red' 'Yellow' 'Green' 'black' 'white']


In [27]:
print(extended)
print("after delete")
upd_arr = np.delete(extended, 1)
print(upd_arr)

['Red' 'Yellow' 'Green' 'black' 'white']
after delete
['Red' 'Green' 'black' 'white']


In [28]:
print(extended)
print("after delete")
upd_arr1 = np.delete(extended, [1, 2])
print(upd_arr1)

['Red' 'Yellow' 'Green' 'black' 'white']
after delete
['Red' 'black' 'white']


In [29]:
int_rand = np.random.randint(1,11, size = (4,5))
print(int_rand)
print("after delete")
aft_del = np.delete(int_rand, 1, axis = 0)
print(aft_del)


[[ 7  7  3  7  1]
 [ 4  6  1  5  2]
 [ 6  8  6  6  8]
 [ 5 10  8  6 10]]
after delete
[[ 7  7  3  7  1]
 [ 6  8  6  6  8]
 [ 5 10  8  6 10]]


In [30]:
int_rand = np.random.randint(1,11, size = (4,5))
print(int_rand)
print("after delete")
aft_del1 = np.delete(int_rand, 1, axis = 1)
print(aft_del1)


[[ 6  3  2  1  2]
 [ 7  8  3  8 10]
 [ 5 10  7  4  2]
 [ 8  2  2 10  7]]
after delete
[[ 6  2  1  2]
 [ 7  3  8 10]
 [ 5  7  4  2]
 [ 8  2 10  7]]
