## 1. Statistical Operations with NumPy

### 1.1. Finding Mean 

In [1]:
import numpy as np

my_array = np.array([2,4,8,10,12])
print(my_array)
print("mean:")
print(np.mean(my_array))


[ 2  4  8 10 12]
mean:
7.2


In [2]:
import numpy as np

my_array = np.random.randint(1,20, size = (2,3))
print(my_array)
print("mean:")
print(np.mean(my_array, axis = 1))
print(np.mean(my_array, axis = 0))

[[ 8 19 18]
 [ 6  2  6]]
mean:
[15.          4.66666667]
[ 7.  10.5 12. ]


### 1.2. Finding Median 

In [3]:
import numpy as np

my_array = np.array([2,4,8,10,12])
print(my_array)
print("median:")
print(np.median(my_array))

[ 2  4  8 10 12]
median:
8.0


In [4]:
import numpy as np

my_array = np.random.randint(1,20, size = (3,5))
print(my_array)
print("median:")
print(np.median(my_array, axis = 1))
print(np.median(my_array, axis = 0))

[[ 3 15 12  2 14]
 [14 18  6  5 16]
 [18 14  6  6  7]]
median:
[12. 14.  7.]
[14. 15.  6.  5. 14.]


### 1.3. Finding Max and Min Values

In [5]:
import numpy as np

my_array = np.array([2,4,8,10,12])
print(my_array)
print("min value:")
print(np.amin(my_array))

[ 2  4  8 10 12]
min value:
2


In [6]:
import numpy as np

my_array = np.random.randint(1,20, size = (3,4))
print(my_array)
print("min:")
print(np.amin(my_array, axis = 1))
print(np.amin(my_array, axis = 0))

[[18 18  8 18]
 [ 5  8 17  8]
 [ 5 15  4 19]]
min:
[8 5 4]
[5 8 4 8]


In [7]:
import numpy as np

my_array = np.array([2,4,8,10,12])
print(my_array)
print("max value:")
print(np.amax(my_array))

[ 2  4  8 10 12]
max value:
12


In [8]:
import numpy as np

my_array = np.random.randint(1,20, size = (3,4))
print(my_array)
print("max:")
print(np.amax(my_array, axis = 1))
print(np.amax(my_array, axis = 0))

[[ 9  3  6  1]
 [13 14  4 14]
 [13 10  5  1]]
max:
[ 9 14 13]
[13 14  6 14]


### 1.4. Finding Standard Deviation

In [9]:
import numpy as np

my_array = np.array([2,4,8,10,12])
print(my_array)
print("std value:")
print(np.std(my_array))

[ 2  4  8 10 12]
std value:
3.7094473981982814


In [10]:
import numpy as np

my_array = np.random.randint(1,20, size = (3,4))
print(my_array)
print("std-dev:")
print(np.std(my_array, axis = 1))
print(np.std(my_array, axis = 0))

[[12 10  9  9]
 [16 12  9  3]
 [ 3 14  5 11]]
std-dev:
[1.22474487 4.74341649 4.43705984]
[5.43650214 1.63299316 1.88561808 3.39934634]


### 1.5. Finding Correlations

In [11]:
import numpy as np

a1 = np.array([1, 3, 0, 0.9, 1.2])
a2 = np.array([-1, 0.5, 0.2, 0.6, 5])

print(a1)
print(a2)

print("correlation value:")
print(np.correlate(a1, a2))

[1.  3.  0.  0.9 1.2]
[-1.   0.5  0.2  0.6  5. ]
correlation value:
[7.04]


## 2. Getting Unique Items and Counts

In [12]:
import numpy as np

my_array  = np.array([5,8,7,5,9,3,7,7,1,1,8,4,6,9,7,3])
unique_items = np.unique(my_array )

print(unique_items)

[1 3 4 5 6 7 8 9]


In [13]:
import numpy as np

my_array  = np.array([5,8,7,5,9,3,7,7,1,1,8,4,6,9,7,3])
unique_items, counts = np.unique(my_array, return_counts=True)

print(unique_items)
print(counts)



[1 3 4 5 6 7 8 9]
[2 2 1 2 1 4 2 2]


In [14]:
frequencies = np.asarray((unique_items, counts))
print(frequencies)

[[1 3 4 5 6 7 8 9]
 [2 2 1 2 1 4 2 2]]


In [15]:
frequencies = np.asarray((unique_items, counts)).T
print(frequencies)

[[1 2]
 [3 2]
 [4 1]
 [5 2]
 [6 1]
 [7 4]
 [8 2]
 [9 2]]


## 3. Importing and Exporting CSV Files

### 3.1. Saving NumPy File as CSV

In [16]:
import numpy as np

my_array = np.random.randint(1,20, size = (3,4))
print(my_array)

my_array.tofile('my_array.csv', sep = ',')

[[14  8 14 16]
 [12 13 14  4]
 [16 14  6 17]]


In [17]:
import numpy as np

my_array = np.random.randint(1,20, size = (3,4))
print(my_array)

np.savetxt('my_array2.csv', my_array, delimiter = ",")

[[12  2 10  5]
 [14  1  4 13]
 [ 3  9  4  6]]


### 3.2. Loading a CSV File as a NumPy Array

In [18]:
import numpy as np

loaded_array = np.genfromtxt('my_array2.csv', delimiter=',')
print(loaded_array)

[[12.  2. 10.  5.]
 [14.  1.  4. 13.]
 [ 3.  9.  4.  6.]]
