## 1. Sorting NumPy Arrays 

### 1.1. Sorting Numeric Arrays

In [1]:
import numpy as np

print("unsorted array")
my_array = np.random.randint(1,20,10)
print(my_array)


unsorted array
[10 17  9 15  6 19 13 18  3  3]


In [2]:
print("\nsorted array")
sorted_array = np.sort(my_array)
print(sorted_array)


sorted array
[ 3  3  6  9 10 13 15 17 18 19]


### 1.2. Sorting Text Arrays

In [3]:
print("unsorted array")
my_array = np.array(["Red", "Green", "Blue", "Yellow"])
print(my_array)



unsorted array
['Red' 'Green' 'Blue' 'Yellow']


In [4]:
print("\nsorted array")
sorted_array = np.sort(my_array)
print(sorted_array)


sorted array
['Blue' 'Green' 'Red' 'Yellow']


### 1.3. Sorting Boolean Arrays

In [5]:
print("unsorted array")
my_array = np.array([False, True, True, False, False, True, False, True])
print(my_array)



unsorted array
[False  True  True False False  True False  True]


In [6]:
print("\nSorted array")
sorted_array = np.sort(my_array)
print(sorted_array)


Sorted array
[False False False False  True  True  True  True]


### 1.4. Sorting 2-D Arrays

In [7]:
print("unsorted array")
my_array = np.random.randint(1,20, size = (4,6))
print(my_array)

print("\nSorted array")
sorted_array = np.sort(my_array)
print(sorted_array)

unsorted array
[[12  7  3  4  5  9]
 [ 7 16  7 16 15  9]
 [17 15 17 15  2  8]
 [17 11 18 19 10  2]]

Sorted array
[[ 3  4  5  7  9 12]
 [ 7  7  9 15 16 16]
 [ 2  8 15 15 17 17]
 [ 2 10 11 17 18 19]]


### 1.5. Sorting in Descending Order

In [8]:
print("unsorted array")
my_array = np.random.randint(1,20,10)
print(my_array)

print("\nsorted array")
sorted_array = np.sort(my_array)
reverse_sorted = np.flipud(sorted_array)
print(reverse_sorted)

unsorted array
[ 7  8 10 10 16 10  7 14  3  3]

sorted array
[16 14 10 10 10  8  7  7  3  3]


## 2. Broadcasting NumPy Arrays

In [9]:
array1 = np.array ([14,25,31])
array2 = np.array([10])
result = array1 + array2 
print(result)

[24 35 41]


In [10]:

array1 = np.random.randint(1,20, size = (3,4))
print(array1)

array2 = np.array([10])

print("\nafter broadcasting")
result = array1 + array2 
print(result)

[[ 2 13  1  3]
 [14 10  9  1]
 [15 16  9 13]]

after broadcasting
[[12 23 11 13]
 [24 20 19 11]
 [25 26 19 23]]


In [11]:

array1 = np.random.randint(1,20, size = (3,4))
print(array1)

array2 = np.array([5,10,20,25])

print("\nafter broadcasting")
result = array1 + array2 
print(result)

[[12 18  8 18]
 [16 19 18 16]
 [ 2  4 15  6]]

after broadcasting
[[17 28 28 43]
 [21 29 38 41]
 [ 7 14 35 31]]


In [12]:
array1 = np.random.randint(1,20, size = (3,4))
print(array1)

array2 = np.array([[5],[10],[20]])

print("\nafter broadcasting")
result = array1 + array2 
print(result)

[[ 8 10  5  9]
 [17 19 14  8]
 [ 7  9  5  8]]

after broadcasting
[[13 15 10 14]
 [27 29 24 18]
 [27 29 25 28]]


## 3. Copying NumPy Arrays

In [13]:
array1 = np.array([10,12,14,16,18,20])

array2 = array1.copy()
array2[1] = 20

print(array1)
print(array2)

[10 12 14 16 18 20]
[10 20 14 16 18 20]


In [14]:
array1 = np.array([10,12,14,16,18,20])

array2 = np.copy(array1)
array2[1] = 20

print(array1)
print(array2)

[10 12 14 16 18 20]
[10 20 14 16 18 20]


In [15]:
array1 = np.array([10,12,14,16,18,20])

array2 = array1.view()
array2[1] = 20

print(array1)
print(array2)

[10 20 14 16 18 20]
[10 20 14 16 18 20]
