## 1. Arithmetic Operations with NumPy

### 1.1. Finding Square Roots

In [1]:
import numpy as np

nums = [10,20,30,40,50]  
np_sqr = np.sqrt(nums)  
print(np_sqr) 

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


### 1.2.Finding Logs

In [2]:
import numpy as np

nums = [10,20,30,40,50]  
np_log = np.log(nums)  
print(np_log )


[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


### 1.3. Finding Exponents

In [3]:
import numpy as np

nums = [10,20,30,40,50]  
np_exp = np.exp(nums)  
print(np_exp)  

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


### 1.4. Finding Since and Cosine

In [4]:
import numpy as np

nums = [10,20,30,40,50]  
np_sine = np.sin(nums)  
print(np_sine)  
 
nums = [10,20,30,40,50]  
np_cos = np.cos(nums)  
print(np_cos)  

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]


## 2. Linear Algebra Operations with NumPy

### 2.1. Finding Matrix Dot Product

In [6]:
import numpy as np

A = np.random.randn(4,5)  
B = np.random.randn(5,4)  
print(A)
print(B)
Z =  np.dot(A,B)   
print(Z)  


[[-0.97759939  1.36206061 -0.71036729  0.1375452   0.4495232 ]
 [-0.0558405  -1.5008877  -0.24412504 -0.70492858  1.88644986]
 [-1.74395602 -0.14506531 -0.42834615  0.82757345 -0.92612155]
 [-0.97356162 -0.63414045 -1.40477055  0.42993315  0.2515148 ]]
[[-1.40048793  1.4720401  -0.44554608 -1.611188  ]
 [ 0.20273594 -1.68594028  2.01669298 -0.06206461]
 [ 2.89431442 -1.08939583 -0.32023773  1.24744001]
 [ 1.81731081 -1.48016504 -0.9262508   0.62135535]
 [ 1.02967167 -0.12609598 -0.22766458 -0.74135575]]
[[ 0.30205217 -3.22181987  3.18016821  0.35662791]
 [-0.27130491  3.51969328 -2.70030927 -1.9579514 ]
 [ 1.723568   -2.96412832  0.06593768  3.48531103]
 [-1.79064959  0.49826533 -0.85072644 -0.06373918]]


### 2.2.	Element-wise Matrix Multiplication

In [7]:
import numpy as np

row1 = [10,12,13]  
row2 = [45,32,16]  
row3 = [45,32,16]  
 
nums_2d = np.array([row1, row2, row3])  
print(nums_2d)

multiply = np.multiply(nums_2d, nums_2d)  
print(multiply)


[[10 12 13]
 [45 32 16]
 [45 32 16]]
[[ 100  144  169]
 [2025 1024  256]
 [2025 1024  256]]


### 2.3. Finding Matrix Inverse

In [8]:
import numpy as np

row1 = [1,2,3]  
row2 = [5,2,8]  
row3 = [9,1,10]  
 
nums_2d = np.array([row1, row2, row3])  
print(nums_2d) 
inverse = np.linalg.inv(nums_2d)  
print(inverse)  

[[ 1  2  3]
 [ 5  2  8]
 [ 9  1 10]]
[[ 0.70588235 -1.          0.58823529]
 [ 1.29411765 -1.          0.41176471]
 [-0.76470588  1.         -0.47058824]]


### 2.4. Finding Matrix Determinant

In [9]:
import numpy as np

row1 = [1,2,3]  
row2 = [5,2,8]  
row3 = [9,1,10]    
    
nums_2d = np.array([row1, row2, row3])    
    
determinant = np.linalg.det(nums_2d)    
print(determinant)    

16.999999999999993


### 2.5. Finding Matrix Trace

In [10]:
import numpy as np

row1 = [1,2,3]  
row2 = [4,5,6]  
row3 = [7,8,9]  
  
nums_2d = np.array([row1, row2, row3])  
print(nums_2d)
trace = np.trace(nums_2d)  
print(trace)  

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


### 2.6. Solving a System of Linear Equations with Python

In [11]:
#two equations

# 6x + 3y = 42
# 2x + 4y = 32


In [12]:
import numpy as np

A = np.array([[6, 3],
              [2, 4]])
 
B = np.array([42, 32])
             

In [13]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.22222222 -0.16666667]
 [-0.11111111  0.33333333]]


In [14]:
X = np.dot(A_inv, B)
print(X)

[4. 6.]
